##
## Starter Kit configuration for Velero
##
configuration:
  # provider is the name for the backup storage location provider.
  provider: aws
  # Parameters for the `default` BackupStorageLocation. See
  # https://velero.io/docs/v1.6/api-types/backupstoragelocation/
  backupStorageLocation:
    # bucket is the name of the bucket to store backups in. Required.
    bucket: <YOUR_DO_SPACES_BUCKET_NAME_HERE>
    config:
      region: <YOUR_DO_SPACES_BUCKET_REGION_HERE> # e.g. nyc1
      s3Url: https://<YOUR_DO_SPACES_BUCKET_REGION_HERE>.digitaloceanspaces.com  # e.g.: https://nyc1.digitaloceanspaces.com 

  # Parameters for the `default` VolumeSnapshotLocation. See
  # https://velero.io/docs/v1.6/api-types/volumesnapshotlocation/
  volumeSnapshotLocation:
    provider: digitalocean.com/velero

  # Additional key/value pairs to be used as environment variables
  extraEnvVars:
    DIGITALOCEAN_TOKEN: <YOUR_DO_API_TOKEN_HERE>

# Info about the DO Spaces credentials to be used by the Velero deployment
credentials:
  secretContents:
    cloud: |
      [default]
      aws_access_key_id=<YOUR_DO_SPACES_ACCESS_KEY_HERE>
      aws_secret_access_key=<YOUR_DO_SPACES_SECRET_KEY_HERE>

# Init containers to add to the Velero deployment's pod spec. At least one plugin provider image is required.
initContainers:
  - name: velero-plugin-for-aws
    image: velero/velero-plugin-for-aws:v1.3.0
    imagePullPolicy: IfNotPresent
    volumeMounts:
      - mountPath: /target
        name: plugins
  - name: velero-plugin
    image: digitalocean/velero-plugin:v1.0.0
    imagePullPolicy: IfNotPresent
    volumeMounts:
      - mountPath: /target
        name: plugins

# Whether to deploy the restic daemonset.
deployRestic: false
